django_quizzer/administration/urls.py
from django.urls import path
from django_quizzer.administration.views import users_list, update_user_to_staff, quizzes_list, create_quiz, edit_quiz, \
    delete_quiz, administration, questions_view, add_question, edit_question, delete_question, add_category

urlpatterns = [
    path('', administration, name='administration'),
    path('users_list/', users_list, name='users_list'),
    path('update_user_to_staff/<str:username>/', update_user_to_staff, name='update_user_to_staff'),

    path('add_category/', add_category, name='add_category'),

    path('quizzes_list/', quizzes_list, name='quizzes_list'),
    path('create_quiz/', create_quiz, name='create_quiz'),
    path('edit_quiz/<int:quiz_id>/', edit_quiz, name='edit_quiz'),
    path('delete_quiz/<int:quiz_id>/', delete_quiz, name='delete_quiz'),

    path('questions/<int:quiz_id>/', questions_view, name='questions'),
    path('add_question/<int:quiz_id>/', add_question, name='add_question'),
    path('edit_question/<int:quiz_id>/<int:question_id>/', edit_question, name='edit_question'),
    path('delete_question/<int:quiz_id>/<int:question_id>/', delete_question, name='delete_question'),
]

django_quizzer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django_quizzer import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django_quizzer.web.urls')),
    path('user/', include('django_quizzer.account.urls')),
    path('quiz/', include('django_quizzer.quiz.urls')),
    path('administration/', include('django_quizzer.administration.urls'))
]

handler404 = 'django_quizzer.web.views.handler404'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_quizzer/administration/models.py
from django.db import models

# Create your models here.

django_quizzer/quiz/models.py
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator
from django.db import models
from django.db.models import Sum
from django.db.models.signals import post_save
from django.dispatch import receiver


class Category(models.Model):
    MAX_NAME_LENGTH = 50
    name = models.CharField(
        max_length=MAX_NAME_LENGTH,
    )

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Quiz(models.Model):
    MAX_TITLE_LENGHT = 100
    title = models.CharField(
        max_length=MAX_TITLE_LENGHT,
    )

    description = models.TextField()

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
    )

    thumbnail = models.URLField(
        blank=True,
        null=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
    )

    class Meta:
        verbose_name_plural = 'Quizzes'

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
    )
    question_text = models.CharField(
        max_length=255
    )
    option_1 = models.CharField(
        max_length=255
    )
    option_2 = models.CharField(
        max_length=255
    )
    option_3 = models.CharField(
        max_length=255)
    option_4 = models.CharField(
        max_length=255
    )
    answer = models.CharField(
        max_length=255
    )

    def __str__(self):
        return self.question_text


class QuizSubmission(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
    )

    score = models.IntegerField()

    submited_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return f'{self.user}, {self.quiz.title}'


class UserRank(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )

    rank = models.IntegerField(
        blank=True,
        null=True,
    )

    total_score = models.IntegerField(
        blank=True,
        null=True,
    )

    def __str__(self):
        return f'{self.rank}, {self.user.username}'


@receiver(post_save, sender=QuizSubmission)
def update_leaderboard(sender, instance, created, **kwargs):
    if created:
        update_leaderboard()


def update_leaderboard():
    user_scores = (QuizSubmission.objects.values('user').annotate(total_score=Sum('score')).order_by('-total_score'))

    rank = 1
    for entry in user_scores:
        user_id = entry['user']
        total_score = entry['total_score']

        user_rank, created = UserRank.objects.get_or_create(user_id=user_id)
        user_rank.rank = rank
        user_rank.total_score = total_score
        user_rank.save()

        rank += 1

django_quizzer/administration/views.py
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.models import User
from django.shortcuts import render, redirect, get_object_or_404
from django_quizzer.account.models import Profile
from django_quizzer.quiz.forms import QuizForm, QuestionForm, CategoryForm
from django_quizzer.quiz.models import Category, Quiz, Question


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def administration(request):
    return render(request, 'administration/administration.html', context={})


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def users_list(request):
    users = User.objects.all().order_by('-date_joined')

    context = {
        'users': users,
    }

    return render(request, 'administration/user_partials/users_list.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def update_user_to_staff(request, username):
    user = get_object_or_404(User, username=username)

    if request.method == 'POST':

        if 'is_staff' in request.POST:
            is_staff = request.POST.get('is_staff') == 'on'
            user.is_staff = is_staff
            user.save()

        else:
            user.is_staff = False
            user.save()

        return redirect('users_list')

    return redirect('users_list')


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def quizzes_list(request):
    quizzes = Quiz.objects.all().order_by('-created_at')
    categories = Category.objects.all().order_by('name')

    context = {
        'quizzes': quizzes,
        'categories': categories,
    }

    return render(request, 'administration/quiz_partials/quizzes_list.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('quizzes_list')
    else:
        form = CategoryForm()

    context = {
        'form': form,
    }

    return render(request, 'administration/category_partials/add_category.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def create_quiz(request):
    user_object = User.objects.get(username=request.user)
    user_profile = Profile.objects.get(user=user_object)
    categories = Category.objects.all().order_by('name')

    if request.method == 'POST':
        form = QuizForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('quizzes_list')
    else:
        form = QuizForm()

    context = {
        'form': form,
        'user_profile': user_profile,
        'categories': categories,
    }

    return render(request, 'administration/quiz_partials/create_quiz.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def edit_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    categories = Category.objects.all().order_by('name')

    if request.method == 'POST':
        form = QuizForm(request.POST, request.FILES, instance=quiz)
        if form.is_valid():
            form.save()
            return redirect('quizzes_list')
    else:
        form = QuizForm(instance=quiz)

    context = {
        'form': form,
        'quiz': quiz,
        'categories': categories,
    }

    return render(request, 'administration/quiz_partials/edit_quiz.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def delete_quiz(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    if request.method == 'POST':
        quiz.delete()
        return redirect('quizzes_list')

    context = {
        'quiz': quiz,
    }

    return render(request, 'administration/quiz_partials/delete_quiz.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def questions_view(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    questions = Question.objects.filter(quiz=quiz).all()
    total_questions = questions.count()

    context = {
        'quiz': quiz,
        'questions': questions,
        'total_questions': total_questions,
    }

    return render(request, 'administration/question_partials/questions.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def add_question(request, quiz_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.quiz = quiz
            question.save()
            return redirect('questions', quiz.id)
    else:
        form = QuestionForm()

    context = {
        'quiz': quiz,
        'form': form,
    }

    return render(request, 'administration/question_partials/add_question.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def edit_question(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            form.save()
            return redirect('questions', quiz_id=quiz.id)
    else:
        form = QuestionForm(instance=question)

    context = {
        'quiz': quiz,
        'form': form,
        'question': question,
    }

    return render(request, 'administration/question_partials/edit_question.html', context)


@user_passes_test(lambda u: u.is_superuser or u.is_staff)
def delete_question(request, quiz_id, question_id):
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    question = get_object_or_404(Question, pk=question_id)

    if request.method == 'POST':
        question.delete()
        return redirect('questions', quiz_id=quiz.id)

templates/administration/quiz_partials/create_quiz.html
{% extends 'base.html' %}

{% block title %}Create Quiz{% endblock %}

{% block main_block %}
    
    <h1 class="display-4 text-center mt-5 mb-4">Create Quiz</h1>

    <div class="container">
    
        <div class="row">
        
            <div class="col">
            </div>
        
            <div class="col-sm-auto col-md">
            
                <form action="{% url 'create_quiz' %}" method="post" enctype="multipart/form-data">
                
                    {% csrf_token %}
                
                    <div class="mb-3 mt-4">
                        <label for="exampleInputTitle" class="form-label">Title</label>
                        <input type="text" name="title" class="form-control" id="exampleInputTitle" required>
                    </div>
                
                    <div class="mb-3">
                        <label for="exampleInputDescription" class="form-label">Description</label>
                        <textarea name="description" class="form-control" id="exampleInputDescription" rows="3"
                                  required></textarea>
                    </div>
                
                    <div class="mb-3">
                        <label for="exampleInputCategory" class="form-label">Category</label>
                        <select name="category" class="form-select" id="exampleInputCategory" required>
                            <option value="" selected disabled>Choose...</option>
                            {% for category in categories %}
                                <option value="{{ category.id }}">{{ category.name }}</option>
                            {% endfor %}
                        </select>
                    </div>
                
                    <div class="mb-3">
                        <label for="exampleInputThumbnail" class="form-label">Thumbnail URL</label>
                        <input type="url" name="thumbnail" class="form-control" id="exampleInputThumbnail">
                    </div>
                
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary mb-4 text-center">Create Quiz</button>
                        <p class="mb-4">Want to go back? <a href="{% url 'quizzes_list' %}">Back to Quizzes</a></p>
                    </div>
                
                </form>

            </div>
        
            <div class="col">
            </div>
        
        </div>
    
    </div>
    
{% endblock %}

templates/administration/quiz_partials/delete_quiz.html
{% extends 'base.html' %}
{% block title %}Delete Quiz{% endblock %}
{% block main_block %}

    <h1 class="display-4 text-center mt-5 mb-4">Delete Quiz</h1>

    <div class="container">
    
        <div class="row">
            
            <div class="col">
            </div>
            
            <div class="col-sm-auto col-md-8">
                
                <p class="fs-4 text-center">Are you sure you want to delete the quiz "{{ quiz.title }}"?</p>
                
                <form action="{% url 'delete_quiz' quiz.id %}" method="post">
                    
                    {% csrf_token %}
                    
                    <div class="text-center">
                        <button type="submit" class="btn btn-danger">Delete</button>
                        <a href="{% url 'quizzes_list' %}" class="btn btn-secondary">Cancel</a>
                    </div>
                    
                </form>
                
            </div>
            
            <div class="col">
            </div>
            
        </div>
    
    </div>
    
    <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

{% endblock %}

templates/administration/quiz_partials/edit_quiz.html
{% extends 'base.html' %}

{% block title %}Edit Quiz{% endblock %}

{% block main_block %}

    <h1 class="display-4 text-center mt-5 mb-4">Edit Quiz</h1>

    <div class="container">
    
        <div class="row">
        
            <div class="col">
            </div>
        
            <div class="col-sm-auto col-md">
            
                <form action="{% url 'edit_quiz' quiz.id %}" method="post" enctype="multipart/form-data">
                
                    {% csrf_token %}
                
                    <div class="mb-3 mt-4">
                        <label for="exampleInputTitle" class="form-label">Title</label>
                        <input type="text" name="title" class="form-control" id="exampleInputTitle" required
                               value="{{ quiz.title }}">
                    </div>
                
                    <div class="mb-3">
                        <label for="exampleInputDescription" class="form-label">Description</label>
                        <textarea name="description" class="form-control" id="exampleInputDescription" rows="3"
                                  required>{{ quiz.description }}</textarea>
                    </div>
                
                    <div class="mb-3">
                        <label for="exampleInputCategory" class="form-label">Category</label>
                    
                        <select name="category" class="form-select" id="exampleInputCategory" required>
                            <option value="" selected disabled>Choose...</option>
                        
                            {% for category in categories %}
                                <option value="{{ category.id }}"
                                        {% if quiz.category == category %}selected{% endif %}>{{ category.name }}</option>
                            {% endfor %}
                        
                        </select>
                    
                    </div>
                
                    <div class="mb-3">
                        <label for="exampleInputThumbnail" class="form-label">Thumbnail URL</label>
                        <input type="url" name="thumbnail" class="form-control" id="exampleInputThumbnail"
                               value="{{ quiz.thumbnail }}">
                    </div>
                
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary mb-4 text-center">Save Changes</button>
                        <p class="mb-4">Want to go back? <a href="{% url 'quizzes_list' %}">Back to Quizzes</a></p>
                    </div>
                
                </form>
            
            </div>
        
            <div class="col">
            </div>
        
        </div>
    
    </div>
    
{% endblock %}

templates/administration/quiz_partials/quizzes_list.html
{% extends 'base.html' %}

{% load static %}

{% block title %}All Quizzes{% endblock %}

{% block main_block %}

    <h1 class="display-4 text-center my-5">Quizzes' Administration</h1>

    <div class="text-center">
        <a href="{% url 'add_category' %}" class="mb-5 mx-1 btn btn-primary" type="button">Add Category</a>
        <a href="{% url 'create_quiz' %}" class="mb-5 mx-1 btn btn-primary" type="button">Create Quiz</a>
    </div>

    <div class="container">

    {% if quizzes|length > 0 %}

        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">

            {% for quiz in quizzes %}

                <div class="col">
                    <div class="card shadow-sm">

                        {% if quiz.thumbnail %}
                            <img class="bd-placeholder-img card-img-top" src="{{ quiz.thumbnail }}"
                                 width="100%" height="225"
                                 alt="">
                        {% else %}
                            <img class="bd-placeholder-img card-img-top"
                                 src="{% static 'images/default_quiz.jpg' %}"
                                 width="100%" height="225"
                                 alt="">
                        {% endif %}

                        <div class="card-body">
                            <h4 class="mb-3">{{ quiz.title }}</h4>
                            <p class="card-text">Total Questions: {{ quiz.question_set.all|length }} </p>
                            {% if quiz.question_set.all|length < 3 %}
                                <p class="card-text text-danger">Listing requires a minimum of 3 questions!</p>
                            {% else %}
                                <p class="card-text text-success">Quiz successfully listed!</p>
                            {% endif %}
                            <p class="card-text">Category: {{ quiz.category.name }}</p>
                            <p class="card-text">{{ quiz.description }}</p>

                            <div class="d-flex justify-content-center">
                                <a href="{% url 'edit_quiz' quiz.id %}" type="button"
                                   class="fs-5 mx-1 btn btn-sm btn-outline-success">Edit</a>
                                <a href="{% url 'questions' quiz.id %}" type="button"
                                   class="fs-5 mx-1 btn btn-sm btn-outline-primary">Questions</a>
                                <a href="{% url 'delete_quiz' quiz.id %}" type="button"
                                   class="fs-5 mx-1 btn btn-sm btn-outline-danger">Delete</a>
                            </div>

                        </div>

                    </div>

                </div>

            {% endfor %}

        </div>

    {% else %}

        <div class="col text-center">
            <p class="text-danger text-center fs-5">Oops! It seems there are no quizzes available.</p>
        </div>

    {% endif %}

    <div class="text-center">
        <a href="{% url 'administration' %}" class="mt-5 btn btn-primary" type="button">Go Back</a>
    </div>

{% endblock %}